name: Generate Dependency Graph

on:
  workflow_dispatch:

jobs:
  gen-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: advanced-security/generate-sbom-action@v1
        id: gensbom
      - uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: ${{steps.gensbom.outputs.fileName}}
