name: Hello Rinat Workflow

on:
  push:
    branches:
      -main

  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hellorinat
        run: echo "Hi, Rinat! How are you doing?"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: goodbye rinat
        run: echo "Hey, Rinat! Goodbye"
        shell: bash
